# Changes here will be overwritten by Copier
_commit: 8170eb2
_src_path: gh:alan-turing-institute/ocf-model-template
model_name: TuringCloudDiffusionModel
repo_name: turing-modified-cloud-diffusion-repo
