model:
  name: "TuringCloudDiffusionModel"
  params:
    history_steps: 3
    model_path: "manchester_prize/ddpm_clouds/bcpp9bf9_unet_small:v0"
validation:
  data_path: "/bask/projects/v/vjgo8416-climate/shared/data/eumetsat/testing2022/2022_test_nonhrv.zarr"
  wandb_project_name: "cloudcasting"
  wandb_run_name: "TuringCloudDiffusionModel-test"
  nan_to_num: False
  batch_size: 2
  num_workers: 0
  batch_limit: 20